

services:
  app:
    image: tranvantai26/full-bank-jk:latest
    ports:
      - "8000:8080"
    environment:
      - ENV_VAR_NAME=value
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
